#!/bin/sh

set -e

script/build

if test -e "./build/index.html";then
    echo "It builds!"
    rm -Rf build
else
    echo "Huh. That's odd. The example site doesn't seem to build."
    exit 1
fi

gem build minima.gemspec
